[cosmic-ray]
module-path = "astroalign.py"
timeout = 60.0
excluded-modules = []
test-command = "pytest tests/test_align.py::TestAlign::test_apply_transform_nddata"

[cosmic-ray.distributor]
name = "local"
