[cosmic-ray]
module-path = "astroalign.py"
timeout = 50.0
excluded-modules = []
test-command = "pytest tests/test_align.py::TestAlign::test_consistent_result"

[cosmic-ray.distributor]
name = "local"
